export const ERRORCODE: { [key: string]: string } = {
  SERVER_ERROR_CODE: 'C-GEN',
  VALIDATION_ERROR_CODE: 'C-VAL',
  DATE_RANGE_CODE: 'C-DRL',
  UNAUTH_ADMIN_LOCATION_CODE: 'C-UA',
  MEAL_NOT_CONFIG: 'M-NT',
  MEAL_INACTIVE: 'M-IA',
  EMPLOYEE_INACTIVE_CODE: 'E-IA',
  ADMIN_NOT_FOUND_CODE: 'A-NF',
  LOCATION_NOT_FOUND_CODE: 'L-NF',
  EMPLOYEE_NOT_FOUND_CODE: 'E-NF',
  OTP_NOT_FOUND_CODE: 'O-NF',
  OTP_INVALID_CODE: 'O-IV',
  MEAL_NOT_FOUND_CODE: 'M-NF',
  EMPLOYEE_CREATION_FAILED_CODE: 'E-CF',
  LAUNDRY_NOT_FOUND_CODE: 'LA-NF',
  LAUNDRY_NOT_UPDATE_CODE: 'LA-NU',
  LAUNDRY_BOOKING_NOT_FOUND_CODE: 'LA-BNU',
  ADDITIONAL_SERVICE_NOT_FOUND_CODE: 'AS-NF',
  ADDITIONAL_SERVICE_NOT_UPDATE_CODE: 'AS-NU',
  LOCATION_ADMIN_LINK_NOT_FOUND_CODE: 'LAL-NF',
  EMPLOYEE_EXISTS_CODE: 'E-EX',
  INVALID_PHONE_CODE: 'I-PH',
  INVALID_EMAIL_CODE: 'I-EM',
  APPROVAL_NOT_FOUND_CODE: 'AP-NF',
  APPROVAL_PERMISSION_DENIED_CODE: 'AP-PD',
  CANNOT_RESEND_APPROVAL_CODE: 'AP-CR',
  RESEND_APPROVAL_CODE: 'AP-RS',
  ACTION_NOT_ALLOWED_CODE: 'AP-NA',
  CSV_MISSING_REQUIRED_FIELDS: 'CSV-MRF',
  CSV_MISSING_CONTACT: 'CSV-MCT',
  CSV_DUPLICATE_ID: 'CSV-DID',
  CSV_INVALID_PHONE: 'CSV-IPH',
  CSV_INVALID_EMAIL: 'CSV-IEM',
  CSV_DUPLICATE_EMAIL: 'CSV-DEM',
  CSV_UNSUPPORTED_FILE: 'CSV-UF',
  CSV_MULTIPLE_FILES: 'CSV-MF',
  CSV_UNAUTHORIZED_LOCATION: 'CSV-UL',
  SMS_DELIVERY_FAILED_CODE: 'SMS-DF',
  EMAIL_DELIVERY_FAILED_CODE: 'EM-DF',
  DATA_NOT_FOUND_FOR_PROVIDED_CONTACT_CODE: 'C-NF',
  INVALID_PASSWORD_CODE: 'I-PW',
  INVALID_INPUT_CODE: 'C-INV',
};
export const ERRORMESSAGE: { [key: string]: string } = {
  MEAL_NOT_CONFIG: 'No meal configuration available for this time',
  ADMIN_NOT_FOUND: 'Admin not found',
  LOCATION_NOT_FOUND: 'Location not found',
  EMPLOYEE_NOT_FOUND: 'Employee not found',
  SERVER_ERROR: 'Internal Server Error',
  MEAL_NOT_FOUND: 'Meal not found',
  OTP_NOT_FOUND: 'OTP not found',
  OTP_INVALID: ' OTP invalid',
  EMPLOYEE_CREATION_FAILED: 'Employee creation failed',
  EMPLOYEE_INACTIVE: 'this employee was not active',
  LAUNDRY_NOT_FOUND: 'Laundry not found',
  LAUNDRY_FIELD_MISSING: 'Each detail entry must contain itemId and quantity',
  LAUNDRY_NOT_UPDATE: 'Laundry not update',
  LAUNDRY_NOT_UPDATE_CREATE_ZERO: 'Laundry not update or create with zero',
  LAUNDRY_BOOKING_NOT_FOUND: 'Laundry booking not found',
  ADDITIONAL_SERVICE_NOT_FOUND: 'Additional service item not found',
  ADDITIONAL_SERVICE_NOT_UPDATE: 'Additional service not update',
  LOCATION_WITH_ADMIN_NOT_FOUND: 'No admin found for the location',
  EMPLOYEE_EXISTS: 'Employee already exists',
  INVALID_EMAIL: 'The provided email is invalid',
  INVALID_PHONE: 'The provided phone number is invalid',
  INVALID_EMAIL_MOBILE: 'The provided email or phone number is invalid',
  APPROVAL_NOT_FOUND: 'No approval data found',
  APPROVAL_PERMISSION_DENIED: 'You are not authorized to perform this action',
  CANNOT_RESEND_APPROVAL:
    'Cannot resend approval for reconsideration, not in approval state',
  UNAUTHORIZED_RESEND_APPROVAL:
    'You are not authorized to resend approval. Only users from the SA organization have this permission',
  RESEND_APPROVAL: 'Approval status re-sent for reconsideration',
  BULK_USER_NO_FILE: 'No file uploaded',
  BULK_USER_CREATE_FILE_FAILED: 'File upload failed',
  ACTION_NOT_ALLOWED: 'Action not allowed',
  CSV_MISSING_REQUIRED_FIELDS:
    'Missing required fields (employee id, name, location, room number) in CSV row',
  CSV_MISSING_CONTACT: 'Either mobile number or email is required',
  CSV_DUPLICATE_ID: 'Duplicate Employee ID found',
  CSV_INVALID_PHONE: 'Invalid phone number format',
  CSV_INVALID_EMAIL: 'Invalid email format',
  CSV_DUPLICATE_EMAIL: 'Email address already exists in system',
  CSV_UNSUPPORTED_FILE: 'Unsupported file type. Only CSV files are allowed',
  CSV_MULTIPLE_FILES:
    'Multiple file upload not supported. Please upload single CSV file only',
  CSV_UNAUTHORIZED_LOCATION:
    'You do not have permission to add employees to this location',
  UNAUTH_ADMIN_LOCATION: 'Unauthorized access for this admin location',
  SMS_DELIVERY_FAILED: 'Failed to deliver the SMS',
  EMAIL_DELIVERY_FAILED: 'Failed to deliver the EMAIL',
  DATE_RANGE_LIMIT:
    'The difference between start and end date cannot exceed 30 days',
  DATA_NOT_FOUND_FOR_PROVIDED_CONTACT:
    'No active user found with provided contact',
  INVALID_PASSWORD: 'The provided password is invalid',
  EMPLOYEE_SHOULD_PROVIDE_OTP: 'Employees must provide a valid OTP',
  ADMIN_SHOULD_PROVIDE_PASSWORD:
    'Admin must provide a valid password for verification',
  INVALID_INPUT_TOKEN_SIGN_IN: 'Invalid input for token sign in',
  INVALID_TOKEN: 'Invalid Token',
};
export const serverError = (error: any) => {
  return {
    success: false,
    errorCode: `${ERRORCODE.SERVER_ERROR_CODE}`,
    errorMessage: error.message || `${ERRORMESSAGE.SERVER_ERROR}`,
  };
};
